services:
  asterisk:
    image: andrius/asterisk:latest
    container_name: sanasterisk
    ports:
      - "5060:5060/udp"
      - "8088:8088"
      - "10000:10000/udp"
      - "10001:10001/udp"
      - "10002:10002/udp"
